
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-15T10:22:49-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb6738cefa63165e2e2a5c1b52f6d2923f314a2e",
 "version": "4.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
