"""
Python MCU Bootloader
~~~~~~~~~~~~~~~~~~~~~

pymdfu is a Python driver for a MCU bootloader
"""
import logging
logging.getLogger(__name__).addHandler(logging.NullHandler())

# Build number part of version will be replaced by build number from Jenkins.
# For local builds the build number is 0 and the 'snapshot' is added as Local Version Identifier
__version__ = '1.0.2.6'

# The GIT commit ID and build date are generated by Jenkins when building the package
COMMIT_ID = '06b6f11b6332bf871a9caaccfff4498e535f7b10'
BUILD_DATE = '2023-12-15 11:27:04'

