from .ahnonlosoio import *
from .answer import *
from .cat import *
from .ciaoruozi import *
from .color import *
from .cv import *
from .diobot import *
from .dog import *
from .emojify import *
from .fiorygi import *
from .fortune import *
from .hack import *
from .login import *
from .loginprogress import *
from .man import *
from .ping import *
from .pmots import *
from .rocoinflip import *
from .ship import *
from .smecds import *
from .spell import *
from .version import *
from .whoami import *
from .roll import *
