# coding: utf-8

"""
    HRA-API

    This API provides programmatic access to data registered to the Human Reference Atlas (HRA). See the [HuBMAP HRA Portal](https://humanatlas.io/) for details.   # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ccf_openapi_client import schemas  # noqa: F401


class SpatialEntityDimensions(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The dimensions of a spatial entity.
    """


    class MetaOapg:
        required = {
            "dimension_units",
            "y_dimension",
            "z_dimension",
            "x_dimension",
        }
        
        class properties:
            x_dimension = schemas.NumberSchema
            y_dimension = schemas.NumberSchema
            z_dimension = schemas.NumberSchema
            dimension_units = schemas.StrSchema
            __annotations__ = {
                "x_dimension": x_dimension,
                "y_dimension": y_dimension,
                "z_dimension": z_dimension,
                "dimension_units": dimension_units,
            }
    
    dimension_units: MetaOapg.properties.dimension_units
    y_dimension: MetaOapg.properties.y_dimension
    z_dimension: MetaOapg.properties.z_dimension
    x_dimension: MetaOapg.properties.x_dimension
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["x_dimension"]) -> MetaOapg.properties.x_dimension: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["y_dimension"]) -> MetaOapg.properties.y_dimension: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["z_dimension"]) -> MetaOapg.properties.z_dimension: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dimension_units"]) -> MetaOapg.properties.dimension_units: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["x_dimension", "y_dimension", "z_dimension", "dimension_units", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["x_dimension"]) -> MetaOapg.properties.x_dimension: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["y_dimension"]) -> MetaOapg.properties.y_dimension: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["z_dimension"]) -> MetaOapg.properties.z_dimension: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dimension_units"]) -> MetaOapg.properties.dimension_units: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["x_dimension", "y_dimension", "z_dimension", "dimension_units", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        dimension_units: typing.Union[MetaOapg.properties.dimension_units, str, ],
        y_dimension: typing.Union[MetaOapg.properties.y_dimension, decimal.Decimal, int, float, ],
        z_dimension: typing.Union[MetaOapg.properties.z_dimension, decimal.Decimal, int, float, ],
        x_dimension: typing.Union[MetaOapg.properties.x_dimension, decimal.Decimal, int, float, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SpatialEntityDimensions':
        return super().__new__(
            cls,
            *_args,
            dimension_units=dimension_units,
            y_dimension=y_dimension,
            z_dimension=z_dimension,
            x_dimension=x_dimension,
            _configuration=_configuration,
            **kwargs,
        )
