# coding: utf-8

"""
    HRA-API

    This API provides programmatic access to data registered to the Human Reference Atlas (HRA). See the [HuBMAP HRA Portal](https://humanatlas.io/) for details.   # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ccf_openapi_client import schemas  # noqa: F401


class TissueSampleCommon(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Properties available in all tissue sample objects.
    """


    class MetaOapg:
        required = {
            "datasets",
            "sampleType",
        }
        
        class properties:
            sampleType = schemas.StrSchema
            
            
            class datasets(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['TissueDataset']:
                        return TissueDataset
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['TissueDataset'], typing.List['TissueDataset']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'datasets':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'TissueDataset':
                    return super().__getitem__(i)
            __annotations__ = {
                "sampleType": sampleType,
                "datasets": datasets,
            }
        additional_properties = schemas.AnyTypeSchema
    
    datasets: MetaOapg.properties.datasets
    sampleType: MetaOapg.properties.sampleType
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["datasets"]) -> MetaOapg.properties.datasets: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sampleType"]) -> MetaOapg.properties.sampleType: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["datasets"], typing_extensions.Literal["sampleType"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["datasets"]) -> MetaOapg.properties.datasets: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sampleType"]) -> MetaOapg.properties.sampleType: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["datasets"], typing_extensions.Literal["sampleType"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        datasets: typing.Union[MetaOapg.properties.datasets, list, tuple, ],
        sampleType: typing.Union[MetaOapg.properties.sampleType, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'TissueSampleCommon':
        return super().__new__(
            cls,
            *_args,
            datasets=datasets,
            sampleType=sampleType,
            _configuration=_configuration,
            **kwargs,
        )

from ccf_openapi_client.model.tissue_dataset import TissueDataset
