# Generated by Django 4.2.7 on 2023-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawranflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifiers',
            name='gnb_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
