# Generated by Django 4.2.6 on 2023-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangotextsplitter", "0002_textsplitter_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="textsplitter",
            name="BackendChoice",
            field=models.TextField(default="openai"),
        ),
    ]
