# Generated by Django 4.2.6 on 2023-11-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangotextsplitter", "0003_textsplitter_backendchoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="textalinea",
            name="titlefontsize",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="textpart",
            name="is_fiche",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="textpart",
            name="is_kamerbrief",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="textpart",
            name="italicchars_ratio",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="textpart",
            name="italicratio_threshold",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="textpart",
            name="nr_italic_chars",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="textpart",
            name="textextractionmethod",
            field=models.TextField(default=""),
        ),
    ]
