# Generated by Django 4.2.7 on 2023-12-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "djangotextsplitter",
            "0004_textalinea_titlefontsize_textpart_is_fiche_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="textsplitter",
            name="nr_regression_tests",
            field=models.IntegerField(default=0),
        ),
    ]
