# Generated by Django 4.2.3 on 2023-12-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0011_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='available_at',
            field=models.DateTimeField(help_text='이용 가능한 날짜입니다.', null=True),
        ),
    ]
