# Form implementation generated from reading ui file '/tmp/tmpbk3sy3t2/jdFlatpakSnapshot-2.2/jdFlatpakSnapshot/ui/WelcomeDialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeDialog(object):
    def setupUi(self, WelcomeDialog):
        WelcomeDialog.setObjectName("WelcomeDialog")
        WelcomeDialog.resize(400, 271)
        self.verticalLayout = QtWidgets.QVBoxLayout(WelcomeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.show_startup_check_box = QtWidgets.QCheckBox(parent=WelcomeDialog)
        self.show_startup_check_box.setObjectName("show_startup_check_box")
        self.verticalLayout.addWidget(self.show_startup_check_box)
        self.button_box = QtWidgets.QDialogButtonBox(parent=WelcomeDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(WelcomeDialog)
        self.button_box.accepted.connect(WelcomeDialog.accept) # type: ignore
        self.button_box.rejected.connect(WelcomeDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WelcomeDialog)

    def retranslateUi(self, WelcomeDialog):
        _translate = QtCore.QCoreApplication.translate
        WelcomeDialog.setWindowTitle(_translate("WelcomeDialog", "Welcome"))
        self.label.setText(_translate("WelcomeDialog", "Welcome to jdFlatpakSnapshot!"))
        self.label_2.setText(_translate("WelcomeDialog", "This Program allows you to create a Snapshot of the Data of a Flatpak."))
        self.label_3.setText(_translate("WelcomeDialog", "You can use this e.g. to play a with the Settings of a Program and when something doesn\'t work, restore the Snapshot."))
        self.label_5.setText(_translate("WelcomeDialog", "This Program only saves the Data of a Flatpak and the Version of the Flatpak, but not the Flatpak itself."))
        self.label_6.setText(_translate("WelcomeDialog", "If you encounter a bug, please report it. You can access the Bug Tracker via ?>Report Bug. Suggestions for improvement are also welcome."))
        self.label_4.setText(_translate("WelcomeDialog", "To get started, select a Flatpak and click \"Create Snapshot\"."))
        self.show_startup_check_box.setText(_translate("WelcomeDialog", "Show this Dialog on Startup"))
