#!/usr/bin/env python3
# -*- coding: utf-8 -*-
""" Class for a Wiz.io integration """

# standard python imports
from enum import Enum


class AssetCategory(Enum):
    """Map Wiz assetTypes with RegScale assetCategories"""

    SERVICE_USAGE_TECHNOLOGY = "Software"
    SECRET = "Software"
    BUCKET = "Software"
    WEB_SERVICE = "Software"
    DB_SERVER = "Hardware"
    LOAD_BALANCER = "Software"
    CLOUD_ORGANIZATION = "Software"
    SUBNET = "Software"
    VIRTUAL_MACHINE = "Hardware"
    TECHNOLOGY = "Software"
    SECRET_CONTAINER = "Software"
    FILE_SYSTEM_SERVICE = "Software"
    KUBERNETES_CLUSTER = "Software"
    ROUTE_TABLE = "Software"
    COMPUTE_INSTANCE_GROUP = "Software"
    HOSTED_TECHNOLOGY = "Software"
    USER_ACCOUNT = "Software"
    DNS_ZONE = "Software"
    VOLUME = "Software"
    SERVICE_ACCOUNT = "Software"
    RESOURCE_GROUP = "Software"
    ACCESS_ROLE = "Software"
    SUBSCRIPTION = "Software"
    SERVICE_CONFIGURATION = "Software"
    VIRTUAL_NETWORK = "Software"
    VIRTUAL_MACHINE_IMAGE = "Software"
    FIREWALL = "Hardware"
    DATABASE = "Software"
    GOVERNANCE_POLICY_GROUP = "Software"
    STORAGE_ACCOUNT = "Software"
    CONFIG_MAP = "Software"
    NETWORK_ADDRESS = "Software"
    NETWORK_INTERFACE = "Software"
    DAEMON_SET = "Software"
    PRIVATE_ENDPOINT = "Software"
    ENDPOINT = "Software"
    DEPLOYMENT = "Software"
    POD = "Software"
    KUBERNETES_STORAGE_CLASS = "Software"
    ACCESS_ROLE_BINDING = "Software"
    KUBERNETES_INGRESS = "Software"
    CONTAINER = "Software"
    CONTAINER_REGISTRY = "Software"
    GOVERNANCE_POLICY = "Software"
    REPLICA_SET = "Software"
    KUBERNETES_SERVICE = "Software"
    KUBERNETES_PERSISTENT_VOLUME_CLAIM = "Software"
    KUBERNETES_PERSISTENT_VOLUME = "Software"
    KUBERNETES_NETWORK_POLICY = "Software"
    KUBERNETES_NODE = "Software"
