"""Make find_time nullable

Revision ID: 113c2444dad4
Revises: e6b0d97063a1
Create Date: 2021-04-25 23:17:50.846179

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '113c2444dad4'
down_revision = 'e6b0d97063a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fiorygi_treasures', 'find_time',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fiorygi_treasures', 'find_time',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    # ### end Alembic commands ###
