"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
This is a commons file containing special proto messages for the
server and client to communicate with each other.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ModuleType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ModuleTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ModuleType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LINEAR: _ModuleType.ValueType  # 0
    CONV2D: _ModuleType.ValueType  # 1
    RELU: _ModuleType.ValueType  # 2
    MAXPOOL2D: _ModuleType.ValueType  # 3
    FLATTEN: _ModuleType.ValueType  # 4
    SOFTMAX: _ModuleType.ValueType  # 5
    BATCHNORM2D: _ModuleType.ValueType  # 6
    DROPOUT: _ModuleType.ValueType  # 7
    CONVTRANSPOSE2D: _ModuleType.ValueType  # 8
    TANH: _ModuleType.ValueType  # 9
    SIGMOID: _ModuleType.ValueType  # 10
    LEAKYRELU: _ModuleType.ValueType  # 11
    ELU: _ModuleType.ValueType  # 12
    SELU: _ModuleType.ValueType  # 13
    PRELU: _ModuleType.ValueType  # 14
    GELU: _ModuleType.ValueType  # 15
    GPT2: _ModuleType.ValueType  # 16

class ModuleType(_ModuleType, metaclass=_ModuleTypeEnumTypeWrapper): ...

LINEAR: ModuleType.ValueType  # 0
CONV2D: ModuleType.ValueType  # 1
RELU: ModuleType.ValueType  # 2
MAXPOOL2D: ModuleType.ValueType  # 3
FLATTEN: ModuleType.ValueType  # 4
SOFTMAX: ModuleType.ValueType  # 5
BATCHNORM2D: ModuleType.ValueType  # 6
DROPOUT: ModuleType.ValueType  # 7
CONVTRANSPOSE2D: ModuleType.ValueType  # 8
TANH: ModuleType.ValueType  # 9
SIGMOID: ModuleType.ValueType  # 10
LEAKYRELU: ModuleType.ValueType  # 11
ELU: ModuleType.ValueType  # 12
SELU: ModuleType.ValueType  # 13
PRELU: ModuleType.ValueType  # 14
GELU: ModuleType.ValueType  # 15
GPT2: ModuleType.ValueType  # 16
global___ModuleType = ModuleType

class _Status:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Status.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    READY: _Status.ValueType  # 0
    RUNNING: _Status.ValueType  # 1
    FINISHED: _Status.ValueType  # 2

class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...

READY: Status.ValueType  # 0
RUNNING: Status.ValueType  # 1
FINISHED: Status.ValueType  # 2
global___Status = Status

@typing_extensions.final
class Tensor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUFFER_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    DTYPE_FIELD_NUMBER: builtins.int
    CHUNKS_FIELD_NUMBER: builtins.int
    buffer: builtins.bytes
    @property
    def size(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    dtype: builtins.str
    chunks: builtins.int
    def __init__(
        self,
        *,
        buffer: builtins.bytes = ...,
        size: collections.abc.Iterable[builtins.int] | None = ...,
        dtype: builtins.str = ...,
        chunks: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["buffer", b"buffer", "chunks", b"chunks", "dtype", b"dtype", "size", b"size"]) -> None: ...

global___Tensor = Tensor
