# Generated by Django 3.1.7 on 2021-10-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_data',
            field=models.JSONField(blank=True, default=dict, help_text='Payload to be sent to webhook endpoint', null=True, verbose_name='Event Data'),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Request Data'),
        ),
        migrations.AlterField(
            model_name='log',
            name='response_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Response Data'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='header_params',
            field=models.JSONField(blank=True, default=dict, help_text='These parameters will be sent back to the webhook endpoint via request header.', null=True, verbose_name='Header Parameters'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='query_params',
            field=models.JSONField(blank=True, default=dict, help_text='These parameters will be sent back to the webhook endpoint via query string.', null=True, verbose_name='Query Parameters'),
        ),
    ]
