# Generated by Django 3.2.9 on 2021-12-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mad_webhooks', '0004_event_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mad_webhooks.log', verbose_name='Log'),
        ),
    ]
