"""
# pyfwimagebuilder - Firmware Image Builder
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

pyfwimagebuilder is a tool and library for building firmware update images for Microchip microcontrollers
"""

# Build number part of version will be replaced by build number from Jenkins.
# For local builds the build number is 0 and the 'snapshot' is added as Local Version Identifier
__version__ = '1.0.1.14'

# The GIT commit ID and build date are generated by Jenkins when building the package
COMMIT_ID = 'fe0e85fe68e65f5c17b52f240bbc2b6c9a28e98b'
BUILD_DATE = '2023-12-01 09:08:31'

import logging
logging.getLogger(__name__).addHandler(logging.NullHandler())
