# __init__.py

from pixel_perfect.image_comparer import image_similarity 
from pixel_perfect.image_comparer import image_similarity_score
from pixel_perfect.utils import assert_elements_screenshots
from pixel_perfect.utils import assert_elements_screenshots_in_custom_screen_size
from pixel_perfect.utils import take_screenshots_by_xpath
from pixel_perfect.utils import take_screenshot_by_xpath_in_desktop
from pixel_perfect.utils import take_screenshot_by_xpath_in_tablet
from pixel_perfect.utils import take_screenshot_by_xpath_in_mobile
from pixel_perfect.utils import take_screenshot_by_xpath_in_custom_screen_size
from pixel_perfect.utils import verify_element
from pixel_perfect.utils import capture_baselines


from pixel_perfect.utils import click_element_by_xpath
from pixel_perfect.utils import get_image_offset_ratio_xpath
from pixel_perfect.utils import get_count
from pixel_perfect.utils import get_image_offset_ratio
from pixel_perfect.utils import get_text_by_xpath
from pixel_perfect.utils import get_element_by_xpath
from pixel_perfect.utils import get_property_by_xpath
from pixel_perfect.utils import get_image_aspect_ratio
from pixel_perfect.utils import get_element_from_desktop
from pixel_perfect.utils import get_element_from_tablet
from pixel_perfect.utils import get_element_from_mobile
from pixel_perfect.utils import take_screenshot
from pixel_perfect.utils import assert_elements_UI
from pixel_perfect.utils import get_actual_loc
from pixel_perfect.utils import get_baseline_loc
from pixel_perfect.utils import take_screenshot

