# Generated by ariadne-codegen
# Source: queries.graphql

from pydantic import Field

from .base_model import BaseModel


class WhoAmI(BaseModel):
    me_device: "WhoAmIMeDevice" = Field(alias="meDevice")


class WhoAmIMeDevice(BaseModel):
    id: str
