# Generated by Django 5.0 on 2023-12-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawranflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiers',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='identifiersstats',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stats',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
