VERSION_YEAR = 2023
VERSION_MONTH = int('12')
VERSION_DAY = int('15')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('26')
MAJOR_VERSION = 1
MINOR_VERSION = 7
PATCH_VERSION = 202312151026
version_date = '2023/12/15 10:26'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
