
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-14T16:38:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "72ea8025854941feeaa279ed1da15afc5198c8a5",
 "version": "0.18.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
