
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-17T18:22:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8baac9a90069b59876d5452bcc3dbb9ae5600dae",
 "version": "v1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
