
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-14T21:47:16+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec22cc21c3007f0ca9c6e110280a50b9bac877a8",
 "version": "0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
