# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commons.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommons.proto\"E\n\x06Tensor\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x02 \x03(\r\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x0e\n\x06\x63hunks\x18\x05 \x01(\x05*\xe2\x01\n\nModuleType\x12\n\n\x06LINEAR\x10\x00\x12\n\n\x06\x43ONV2D\x10\x01\x12\x08\n\x04RELU\x10\x02\x12\r\n\tMAXPOOL2D\x10\x03\x12\x0b\n\x07\x46LATTEN\x10\x04\x12\x0b\n\x07SOFTMAX\x10\x05\x12\x0f\n\x0b\x42\x41TCHNORM2D\x10\x06\x12\x0b\n\x07\x44ROPOUT\x10\x07\x12\x13\n\x0f\x43ONVTRANSPOSE2D\x10\x08\x12\x08\n\x04TANH\x10\t\x12\x0b\n\x07SIGMOID\x10\n\x12\r\n\tLEAKYRELU\x10\x0b\x12\x07\n\x03\x45LU\x10\x0c\x12\x08\n\x04SELU\x10\r\x12\t\n\x05PRELU\x10\x0e\x12\x08\n\x04GELU\x10\x0f\x12\x08\n\x04GPT2\x10\x10*.\n\x06Status\x12\t\n\x05READY\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commons_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODULETYPE']._serialized_start=89
  _globals['_MODULETYPE']._serialized_end=315
  _globals['_STATUS']._serialized_start=317
  _globals['_STATUS']._serialized_end=363
  _globals['_TENSOR']._serialized_start=17
  _globals['_TENSOR']._serialized_end=86
# @@protoc_insertion_point(module_scope)
