# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/20_data.ipynb.

# %% auto 0
__all__ = ['index']

# %% ../nbs/20_data.ipynb 6
#| export


# %% ../nbs/20_data.ipynb 8
from typing import TypeAlias

# %% ../nbs/20_data.ipynb 10
#| export


# %% ../nbs/20_data.ipynb 12
from ptyp import Alias, Not

# %% ../nbs/20_data.ipynb 14
from .bool import bools
from .nums import nums
from .nans import nan

# %% ../nbs/20_data.ipynb 16
@Alias(list, bools, nums)
class index: ...
