
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-08T08:51:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a7b25691e4b466809b1527521c5db3c32898b5e",
 "version": "2.10.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
