# flake8: noqa

# import apis into api package
from ionoscloud_container_registry.api.artifacts_api import ArtifactsApi
from ionoscloud_container_registry.api.locations_api import LocationsApi
from ionoscloud_container_registry.api.names_api import NamesApi
from ionoscloud_container_registry.api.registries_api import RegistriesApi
from ionoscloud_container_registry.api.repositories_api import RepositoriesApi
from ionoscloud_container_registry.api.tokens_api import TokensApi
from ionoscloud_container_registry.api.vulnerabilities_api import VulnerabilitiesApi

