
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-12T12:53:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a90ac68605bcb0af0867b4e6b0eb5a08ff86d1d8",
 "version": "2.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
