
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-09T18:38:43+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "4ba7f8697d56081ef5823420bd2b634add4f5418",
 "version": "0.post222.dev0+g4ba7f86"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
