"""
Python MCU Bootloader
~~~~~~~~~~~~~~~~~~~~~

pymdfu is a Python driver for a MCU bootloader
"""
import logging
logging.getLogger(__name__).addHandler(logging.NullHandler())

# Build number part of version will be replaced by build number from Jenkins.
# For local builds the build number is 0 and the 'snapshot' is added as Local Version Identifier
__version__ = '1.0.1.5'

# The GIT commit ID and build date are generated by Jenkins when building the package
COMMIT_ID = '1f15f1ec8a79e89c23529ff2bb5ee1965eb0751f'
BUILD_DATE = '2023-12-13 09:26:01'

