"""
This type stub file was generated by pyright.
"""

from typing import Callable, List

def parallelize(
    strategy: Callable[[List[str]], List[str]], data: List[str], max_workers: int
) -> List[str]:
    """Parallelize a pipeline with Python multiprocessing."""
    ...

def relaxed_clean(data: List[str]) -> List[str]: ...
def strict_clean(data: List[str]) -> List[str]: ...
def extreme_clean(data: List[str]) -> List[str]: ...
