# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.volume_host_path_projected_sources_inner import VolumeHostPathProjectedSourcesInner
from openapi_server import util

from openapi_server.models.volume_host_path_projected_sources_inner import VolumeHostPathProjectedSourcesInner  # noqa: E501

class VolumeHostPathProjected(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sources=None):  # noqa: E501
        """VolumeHostPathProjected - a model defined in OpenAPI

        :param sources: The sources of this VolumeHostPathProjected.  # noqa: E501
        :type sources: List[VolumeHostPathProjectedSourcesInner]
        """
        self.openapi_types = {
            'sources': List[VolumeHostPathProjectedSourcesInner]
        }

        self.attribute_map = {
            'sources': 'sources'
        }

        self._sources = sources

    @classmethod
    def from_dict(cls, dikt) -> 'VolumeHostPathProjected':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Volume_host_path_projected of this VolumeHostPathProjected.  # noqa: E501
        :rtype: VolumeHostPathProjected
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sources(self):
        """Gets the sources of this VolumeHostPathProjected.


        :return: The sources of this VolumeHostPathProjected.
        :rtype: List[VolumeHostPathProjectedSourcesInner]
        """
        return self._sources

    @sources.setter
    def sources(self, sources):
        """Sets the sources of this VolumeHostPathProjected.


        :param sources: The sources of this VolumeHostPathProjected.
        :type sources: List[VolumeHostPathProjectedSourcesInner]
        """

        self._sources = sources
