# Generated by Django 5.0 on 2023-12-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawranflow', '0002_alter_identifiers_id_alter_identifiersstats_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifiers',
            name='f1ap_cause',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='identifiers',
            name='ngap_cause',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='identifiersstats',
            name='gnb_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='f1ap_cause',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='gnb_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='ngap_cause',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='gnb_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='identifiersstats',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier_stats', to='drawranflow.identifiers'),
        ),
    ]
