
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-14T19:35:44-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6de9da87b708edeb077a522a3c3605141b8ac7c4",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
