
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-14T20:37:49-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5a1c697404c985c42e37685a0f8c0a44e83b5c3",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
