langs = {
    "Amharic": "am",
    "Arabic": "ar",
    "Armenian": "hy",
    "Azerbaijani": "az",
    "Bajan": "bjs",
    "Balkan Gipsy": "rm",
    "Basque": "eu",
    "Bemba": "bem",
    "Bengali": "bn",
    "Bielarus": "be",
    "Bislama": "bi",
    "Bosnian": "bs",
    "Breton": "br",
    "Bulgarian": "bg",
    "Burmese": "my",
    "Catalan": "ca",
    "Cebuano": "ceb",
    "Chamorro": "ch",
    "Chinese (Simplified)": "zh",
    "Chinese Traditional": "zh",
    "Comorian (Ngazidja)": "zdj",
    "Coptic": "cop",
    "Creole English (Antigua and Barbuda)": "aig",
    "Creole English (Bahamas)": "bah",
    "Creole English (Grenadian)": "gcl",
    "Creole English (Guyanese)": "gyn",
    "Creole English (Jamaican)": "jam",
    "Creole English (Vincentian)": "svc",
    "Creole English (Virgin Islands)": "vic",
    "Creole French (Haitian)": "ht",
    "Creole French (Saint Lucian)": "acf",
    "Creole French (Seselwa)": "crs",
    "Creole Portuguese (Upper Guinea)": "pov",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Dutch": "nl",
    "Dzongkha": "dz",
    "English": "en",
    "Esperanto": "eo",
    "Estonian": "et",
    "Fanagalo": "fn",
    "Faroese": "fo",
    "Finnish": "fi",
    "French": "fr",
    "Galician": "gl",
    "Georgian": "ka",
    "German": "de",
    "Greek": "el",
    "Greek (Classical)": "grc",
    "Gujarati": "gu",
    "Hausa": "ha",
    "Hawaiian": "haw",
    "Hebrew": "he",
    "Hindi": "hi",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Indonesian": "id",
    "Inuktitut (Greenlandic)": "kl",
    "Irish Gaelic": "ga",
    "Italian": "it",
    "Japanese": "ja",
    "Javanese": "jv",
    "Kabuverdianu": "kea",
    "Kabylian": "kab",
    "Kannada": "kn",
    "Kazakh": "kk",
    "Khmer": "km",
    "Kinyarwanda": "rw",
    "Kirundi": "rn",
    "Korean": "ko",
    "Kurdish": "ku",
    "Kurdish Sorani": "ckb",
    "Kyrgyz": "ky",
    "Lao": "lo",
    "Latin": "la",
    "Latvian": "lv",
    "Lithuanian": "lt",
    "Luxembourgish": "lb",
    "Macedonian": "mk",
    "Malagasy": "mg",
    "Malay": "ms",
    "Maldivian": "dv",
    "Maltese": "mt",
    "Manx Gaelic": "gv",
    "Maori": "mi",
    "Marshallese": "mh",
    "Mende": "men",
    "Mongolian": "mn",
    "Morisyen": "mfe",
    "Nepali": "ne",
    "Niuean": "niu",
    "Norwegian": "no",
    "Nyanja": "ny",
    "Pakistani": "ur",
    "Palauan": "pau",
    "Panjabi": "pa",
    "Papiamentu": "pap",
    "Pashto": "ps",
    "Persian": "fa",
    "Pijin": "pis",
    "Polish": "pl",
    "Portuguese": "pt",
    "Potawatomi": "pot",
    "Quechua": "qu",
    "Romanian": "ro",
    "Russian": "ru",
    "Samoan": "sm",
    "Sango": "sg",
    "Scots Gaelic": "gd",
    "Serbian": "sr",
    "Shona": "sn",
    "Sinhala": "si",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Somali": "so",
    "Sotho, Southern": "st",
    "Spanish": "es",
    "Sranan Tongo": "srn",
    "Swahili": "sw",
    "Swedish": "sv",
    "Swiss German": "de",
    "Syriac (Aramaic)": "syc",
    "Tagalog": "tl",
    "Tajik": "tg",
    "Tamashek (Tuareg)": "tmh",
    "Tamil": "ta",
    "Telugu": "te",
    "Tetum": "tet",
    "Thai": "th",
    "Tibetan": "bo",
    "Tigrinya": "ti",
    "Tok Pisin": "tpi",
    "Tokelauan": "tkl",
    "Tongan": "to",
    "Tswana": "tn",
    "Turkish": "tr",
    "Turkmen": "tk",
    "Tuvaluan": "tvl",
    "Ukrainian": "uk",
    "Uma": "ppk",
    "Uzbek": "uz",
    "Vietnamese": "vi",
    "Wallisian": "wls",
    "Welsh": "cy",
    "Wolof": "wo",
    "Xhosa": "xh",
    "Yiddish": "yi",
    "Zulu": "zu",
}
