
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-12T08:51:23+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "76106d4d806337cb5016fd95e5f41c7056e07044",
 "version": "0.1.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
