
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-13T13:19:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c50c2671d0fa63e0c3fedaac39e36f30ceaa51a2",
 "version": "1.2.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
