# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['web',
 'web.framework',
 'web.framework.templates',
 'web.headers',
 'web.host',
 'web.host.admin',
 'web.host.admin.templates',
 'web.host.templates',
 'web.markdown',
 'web.response',
 'web.templating']

package_data = \
{'': ['*'],
 'web.framework': ['static/measure.png',
                   'static/measure.png',
                   'static/measure.png',
                   'static/measure.png',
                   'static/measure.png',
                   'static/measure.png',
                   'static/measure.png',
                   'static/measure.png',
                   'static/solarized-site.css',
                   'static/solarized-site.css',
                   'static/solarized-site.css',
                   'static/solarized-site.css',
                   'static/solarized-site.css',
                   'static/solarized-site.css',
                   'static/solarized-site.css',
                   'static/solarized-site.css',
                   'static/solarized.css',
                   'static/solarized.css',
                   'static/solarized.css',
                   'static/solarized.css',
                   'static/solarized.css',
                   'static/solarized.css',
                   'static/solarized.css',
                   'static/solarized.css',
                   'static/sw.min.js',
                   'static/sw.min.js',
                   'static/sw.min.js',
                   'static/sw.min.js',
                   'static/sw.min.js',
                   'static/sw.min.js',
                   'static/sw.min.js',
                   'static/sw.min.js',
                   'static/ubuntu-mono-powerline.woff2',
                   'static/ubuntu-mono-powerline.woff2',
                   'static/ubuntu-mono-powerline.woff2',
                   'static/ubuntu-mono-powerline.woff2',
                   'static/ubuntu-mono-powerline.woff2',
                   'static/ubuntu-mono-powerline.woff2',
                   'static/ubuntu-mono-powerline.woff2',
                   'static/ubuntu-mono-powerline.woff2',
                   'static/vosk-recognizer-processor.js',
                   'static/vosk-recognizer-processor.js',
                   'static/vosk-recognizer-processor.js',
                   'static/vosk-recognizer-processor.js',
                   'static/vosk-recognizer-processor.js',
                   'static/vosk-recognizer-processor.js',
                   'static/vosk-recognizer-processor.js',
                   'static/vosk-recognizer-processor.js',
                   'static/web.css',
                   'static/web.css',
                   'static/web.css',
                   'static/web.css',
                   'static/web.css',
                   'static/web.css',
                   'static/web.css',
                   'static/web.css',
                   'static/web.js',
                   'static/web.js',
                   'static/web.js',
                   'static/web.js',
                   'static/web.js',
                   'static/web.js',
                   'static/web.js',
                   'static/web.js']}

install_requires = \
['PySide6>=6.4.2,<7.0.0',
 'Pygments>=2.14.0,<3.0.0',
 'Unidecode>=1.3.6,<2.0.0',
 'acme-tiny>=5.0.1,<6.0.0',
 'bgq>=0.1.3,<0.2.0',
 'cryptography<39',
 'dnspython==2.3.0',
 'easyuri>=0.1.2,<0.2.0',
 'emoji>=2.2.0,<3.0.0',
 'gevent>=23.7.0',
 'gunicorn>=20.1.0,<21.0.0',
 'jsonpatch>=1.32,<2.0',
 'microformats>=0.3.5,<0.4.0',
 'newmath>=0.2.1,<0.3.0',
 'pendulum>=2.1.2,<3.0.0',
 'pillow>=10.0.0,<11.0.0',
 'pycryptodome>=3.16.0,<4.0.0',
 'pynacl>=1.5.0,<2.0.0',
 'python-dotenv>=0.21.1,<0.22.0',
 'python-whois>=0.8.0,<0.9.0',
 'regex>=2022.10.31,<2023.0.0',
 'restrictedpython>=6.0,<7.0',
 'semver>=2.13.0,<3.0.0',
 'sqlyte>=0.1.1,<0.2.0',
 'toml>=0.10.2,<0.11.0',
 'txtint>=0.1.2,<0.2.0',
 'waitress>=2.1.2,<3.0.0',
 'watchdog>=2.2.1,<3.0.0',
 'webagt>=0.1.1,<0.2.0']

entry_points = \
{'console_scripts': ['web = web.__main__:main']}

setup_kwargs = {
    'name': 'webint',
    'version': '0.1.94',
    'description': 'an opinionated web framework that stays out of your way',
    'long_description': '`webint` helps you build a web interface.\n\n## Usage\n\n    mkdir example.site && cd example.site\n    poetry init --name=example-site\n    poetry add webint\n    poetry run web scaffold\n    poetry version minor\n    poetry publish\n    \n    web config --host digitalocean --token {YOUR_TOKEN}\n    web init example.site example-site example:app\n\n### Hack\n\n    poetry run web run example:app --port 9999\n\nChanges to your python code will auto-reload the local development server.\n\n#### Deploy an update\n\n    poetry version (major|minor|patch)\n    poetry publish\n\nWait a couple minutes and update your site at https://example.site/system/software\n',
    'author': 'Angelo Gladding',
    'author_email': 'angelo@ragt.ag',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://ragt.ag/code/projects/webint',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.10,<3.11',
}


setup(**setup_kwargs)
