__license__ = '''
sodom
Copyright (C) 2023  Dmitry Protasov (inbox@protaz.ru)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation, either version 3 of
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General
Public License along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''

from sodom.classes import NormalElement as __NormalElement
from sodom.classes import VoidElement as __VoidElement


a = __NormalElement.partial('a')
abbr = __NormalElement.partial('abbr')
acronym = __NormalElement.partial('acronym')
address = __NormalElement.partial('address')
article = __NormalElement.partial('article')
aside = __NormalElement.partial('aside')
audio = __NormalElement.partial('audio')
b = __NormalElement.partial('b')
bdi = __NormalElement.partial('bdi')
bdo = __NormalElement.partial('bdo')
big = __NormalElement.partial('big')
blockquote = __NormalElement.partial('blockquote')
body = __NormalElement.partial('body')
button = __NormalElement.partial('button')
canvas = __NormalElement.partial('canvas')
caption = __NormalElement.partial('caption')
center = __NormalElement.partial('center')
cite = __NormalElement.partial('cite')
code = __NormalElement.partial('code')
colgroup = __NormalElement.partial('colgroup')
data = __NormalElement.partial('data')
datalist = __NormalElement.partial('datalist')
dd = __NormalElement.partial('dd')
del_ = __NormalElement.partial('del')
details = __NormalElement.partial('details')
dfn = __NormalElement.partial('dfn')
dialog = __NormalElement.partial('dialog')
dir_ = __NormalElement.partial('dir')
div = __NormalElement.partial('div')
dl = __NormalElement.partial('dl')
dt = __NormalElement.partial('dt')
em = __NormalElement.partial('em')
fieldset = __NormalElement.partial('fieldset')
figcaption = __NormalElement.partial('figcaption')
figure = __NormalElement.partial('figure')
font = __NormalElement.partial('font')
footer = __NormalElement.partial('footer')
form = __NormalElement.partial('form')
frame = __NormalElement.partial('frame')
frameset = __NormalElement.partial('frameset')
h1 = __NormalElement.partial('h1')
h2 = __NormalElement.partial('h2')
h3 = __NormalElement.partial('h3')
h4 = __NormalElement.partial('h4')
h5 = __NormalElement.partial('h5')
h6 = __NormalElement.partial('h6')
head = __NormalElement.partial('head')
header = __NormalElement.partial('header')
hgroup = __NormalElement.partial('hgroup')
html = __NormalElement.partial('html')
i = __NormalElement.partial('i')
iframe = __NormalElement.partial('iframe')
image = __NormalElement.partial('image')
ins = __NormalElement.partial('ins')
kbd = __NormalElement.partial('kbd')
label = __NormalElement.partial('label')
legend = __NormalElement.partial('legend')
li = __NormalElement.partial('li')
main = __NormalElement.partial('main')
map_ = __NormalElement.partial('map')
mark = __NormalElement.partial('mark')
marquee = __NormalElement.partial('marquee')
menu = __NormalElement.partial('menu')
menuitem = __NormalElement.partial('menuitem')
meter = __NormalElement.partial('meter')
nav = __NormalElement.partial('nav')
nobr = __NormalElement.partial('nobr')
noembed = __NormalElement.partial('noembed')
noframes = __NormalElement.partial('noframes')
noscript = __NormalElement.partial('noscript')
object_ = __NormalElement.partial('object')
ol = __NormalElement.partial('ol')
optgroup = __NormalElement.partial('optgroup')
option = __NormalElement.partial('option')
output = __NormalElement.partial('output')
p = __NormalElement.partial('p')
picture = __NormalElement.partial('picture')
plaintext = __NormalElement.partial('plaintext')
portal = __NormalElement.partial('portal')
pre = __NormalElement.partial('pre')
progress = __NormalElement.partial('progress')
q = __NormalElement.partial('q')
rb = __NormalElement.partial('rb')
rp = __NormalElement.partial('rp')
rt = __NormalElement.partial('rt')
rtc = __NormalElement.partial('rtc')
ruby = __NormalElement.partial('ruby')
s = __NormalElement.partial('s')
samp = __NormalElement.partial('samp')
script = __NormalElement.partial('script')
search = __NormalElement.partial('search')
section = __NormalElement.partial('section')
select = __NormalElement.partial('select')
slot = __NormalElement.partial('slot')
small = __NormalElement.partial('small')
span = __NormalElement.partial('span')
strike = __NormalElement.partial('strike')
strong = __NormalElement.partial('strong')
style = __NormalElement.partial('style')
sub = __NormalElement.partial('sub')
summary = __NormalElement.partial('summary')
sup = __NormalElement.partial('sup')
table = __NormalElement.partial('table')
tbody = __NormalElement.partial('tbody')
td = __NormalElement.partial('td')
template = __NormalElement.partial('template')
textarea = __NormalElement.partial('textarea')
tfoot = __NormalElement.partial('tfoot')
th = __NormalElement.partial('th')
thead = __NormalElement.partial('thead')
time = __NormalElement.partial('time')
title = __NormalElement.partial('title')
tr = __NormalElement.partial('tr')
tt = __NormalElement.partial('tt')
u = __NormalElement.partial('u')
ul = __NormalElement.partial('ul')
var = __NormalElement.partial('var')
video = __NormalElement.partial('video')
xmp = __NormalElement.partial('xmp')

area = __VoidElement.partial('area')
base = __VoidElement.partial('base')
br = __VoidElement.partial('br')
col = __VoidElement.partial('col')
embed = __VoidElement.partial('embed')
hr = __VoidElement.partial('hr')
img = __VoidElement.partial('img')
input_ = __VoidElement.partial('input')
link = __VoidElement.partial('link')
meta = __VoidElement.partial('meta')
param = __VoidElement.partial('param')
source = __VoidElement.partial('source')
track = __VoidElement.partial('track')
wbr = __VoidElement.partial('wbr')
