= Mapping

`oenv2config` avant d'utiliser les variables d'environement applique des fonctions de mapping. +
Ces fonctions ont comme but de rationaliser plusieur variable dans une seule.

NOTE: La liste complete des variables utilisées, et en quel xref:index.adoc#odoo_cli_type_arg[argument] ou xref:index.adoc#odoo_cli_type_flag[flag] de CLI d'odoo ce trouve xref:index_env.adoc[ici]

Tous les mapping suivant sont appliqués, il faut lire cette documentation comme suit:

NOTE: La variable finale fait partie de la liste a tester car elle peut aussi se trouver dans xref:variable_env[l'environment]

.Exemple pour `DB_NAME`
----
DB_NAME <1>
1. DB_NAME <2>
2. DATABASE <2>
3. POSTGRESQL_ADDON_DB <2>
4. POSTGRES_DB <2>
----
<.> Le nom de la variable final
<.> Variables testées par ordre de priorité




[[mapping_db]]
== Mapping Database

.*DB_NAME*
. DB_NAME
. DATABASE
. POSTGRESQL_ADDON_DB
. POSTGRES_DB

.*DB_HOST*
. DB_HOST
. POSTGRESQL_ADDON_DIRECT_HOST
. POSTGRESQL_ADDON_HOST

.*DB_PORT*
. DB_PORT
. POSTGRESQL_ADDON_DIRECT_PORT
. POSTGRESQL_ADDON_PORT

.*DB_USER*
. DB_USER
. POSTGRESQL_ADDON_USER
. POSTGRES_USER

.*DB_PASSWORD*
. DB_PASSWORD
. POSTGRESQL_ADDON_PASSWORD
. POSTGRES_PASSWORD

[[mapping_http]]
== Mapping Http

.*HTTP_INTERFACE*
. HTTP_INTERFACE
. XMLRPC_INTERFACE

.*HTTP_PORT*
. HTTP_PORT
. XMLRPC_PORT

.*HTTP_ENABLE*
. HTTP_ENABLE
. XMLRPC_ENABLE
