
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-12T15:01:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "459c3b929ec4540c815aca52eed441f33bddb083",
 "version": "3.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
