
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-12T15:16:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ba713984396d88f3560d699e8b7482c4f990b03",
 "version": "1.0.51"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
