from enum import Enum


class LookupPermissionshipRepresentsWhetherALookupResponseWasPartiallyEvaluatedOrNot(str, Enum):
    LOOKUP_PERMISSIONSHIP_CONDITIONAL_PERMISSION = "LOOKUP_PERMISSIONSHIP_CONDITIONAL_PERMISSION"
    LOOKUP_PERMISSIONSHIP_HAS_PERMISSION = "LOOKUP_PERMISSIONSHIP_HAS_PERMISSION"
    LOOKUP_PERMISSIONSHIP_UNSPECIFIED = "LOOKUP_PERMISSIONSHIP_UNSPECIFIED"

    def __str__(self) -> str:
        return str(self.value)
