
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-12T17:22:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f48f3fa0f58b8ab4fd64bc8a0afc9ba5aa45f5d",
 "version": "0.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
